# Postgres image with db label and efforia labeled bridge network
# docker network create --driver bridge efforia
# docker run -d -p 5432:5432 --name db --net=efforia postgres
version: '2'
services:
  store:
    image: efforia/cartridge
    command: deploy/entrypoint.sh
    working_dir: /app 
    container_name: store
    network_mode: "efforia"
    volumes:
      - ..:/app/
    external_links:
      - db:postgres
